services:
    ygw8ckg4w8gw4c404ow8sk0s-220233386910:
        image: 'ygw8ckg4w8gw4c404ow8sk0s:a283c53f695f1401c65310ba6dabdb516890ac87'
        container_name: ygw8ckg4w8gw4c404ow8sk0s-220233386910
        restart: unless-stopped
        expose:
            - '80'
        networks:
            coolify:
                aliases:
                    - ygw8ckg4w8gw4c404ow8sk0s-220233386910
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-ygw8ckg4w8gw4c404ow8sk0s.entryPoints=http
            - traefik.http.routers.http-0-ygw8ckg4w8gw4c404ow8sk0s.middlewares=gzip
            - 'traefik.http.routers.http-0-ygw8ckg4w8gw4c404ow8sk0s.rule=Host(`ygw8ckg4w8gw4c404ow8sk0s.91.99.92.174.sslip.io`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-ygw8ckg4w8gw4c404ow8sk0s.service=http-0-ygw8ckg4w8gw4c404ow8sk0s
            - traefik.http.routers.http-1-ygw8ckg4w8gw4c404ow8sk0s.entryPoints=http
            - traefik.http.routers.http-1-ygw8ckg4w8gw4c404ow8sk0s.middlewares=redirect-to-https
            - 'traefik.http.routers.http-1-ygw8ckg4w8gw4c404ow8sk0s.rule=Host(`ptrck.nl`) && PathPrefix(`/`)'
            - traefik.http.routers.http-1-ygw8ckg4w8gw4c404ow8sk0s.service=http-1-ygw8ckg4w8gw4c404ow8sk0s
            - traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.entryPoints=https
            - traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.middlewares=gzip
            - 'traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.rule=Host(`ptrck.nl`) && PathPrefix(`/`)'
            - traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.service=https-1-ygw8ckg4w8gw4c404ow8sk0s
            - traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.tls.certresolver=letsencrypt
            - traefik.http.routers.https-1-ygw8ckg4w8gw4c404ow8sk0s.tls=true
            - traefik.http.services.http-0-ygw8ckg4w8gw4c404ow8sk0s.loadbalancer.server.port=80
            - traefik.http.services.http-1-ygw8ckg4w8gw4c404ow8sk0s.loadbalancer.server.port=80
            - traefik.http.services.https-1-ygw8ckg4w8gw4c404ow8sk0s.loadbalancer.server.port=80
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 80}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=http://ygw8ckg4w8gw4c404ow8sk0s.91.99.92.174.sslip.io'
            - 'caddy_1.encode=zstd gzip'
            - 'caddy_1.handle_path.1_reverse_proxy={{upstreams 80}}'
            - 'caddy_1.handle_path=/*'
            - caddy_1.header=-Server
            - 'caddy_1.try_files={path} /index.html /index.php'
            - 'caddy_1=https://ptrck.nl'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.452
            - coolify.applicationId=7
            - coolify.type=application
            - coolify.name=ygw8ckg4w8gw4c404ow8sk0s
            - coolify.resourceName=ptrck-nl
            - coolify.projectName=wordpress
            - coolify.serviceName=ptrck-nl
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
